name: Test Course Definition

on:
  workflow_call:
    inputs:
      sdkRef:
        required: false
        type: string
        default: main

jobs:
  identify_language_slugs:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    outputs:
      language_slugs: ${{ steps.generate-language-slugs.outputs.language_slugs }}

    steps:
      - uses: actions/checkout@v3

      - name: Generate Language Slugs
        id: generate-language-slugs
        run: |-
          LANGUAGE_SLUGS=$(ls solutions | jq -Rnc '[inputs]')
          echo ::set-output name=language_slugs::${LANGUAGE_SLUGS}

  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    timeout-minutes: 20

    needs:
      - identify_language_slugs

    strategy:
      matrix:
        language: ${{ fromJSON(needs.identify_language_slugs.outputs.language_slugs) }}

    steps:
      - uses: oven-sh/setup-bun@v1

      - uses: actions/checkout@v3
        with:
          repository: "andy1li/course-sdk"
          ref: ${{inputs.sdkRef}}

      - run: bun install
      - run: make install

      - uses: actions/checkout@v3
        with:
          path: courses/${{github.event.repository.name}}

      - run: "echo ::remove-matcher owner=go::" # Messes with our output

      # - uses: depot/setup-action@v1
      # - uses: depot/build-push-action@v1
      #   with:
      #     project: tsp80qbtxw
      #     context: .
      #     load: true
      #     tags: tester:depot

      - run: git config --global user.email "hello@codecrafters.io"
      - run: git config --global user.name "codecrafters-bot"

      - name: course-sdk-test
        run: |
          echo repo.name: ${{github.event.repository.name}}
          prefix="build-your-own-"
          repo=${{github.event.repository.name}}
          slug="${repo#$prefix}"
          echo slug: $slug
          course-sdk test ${{matrix.language}} && cp -r /tmp/testers/$slug $HOME/
        shell: bash
        working-directory: courses/${{github.event.repository.name}}

      - name: sanity-check
        run: |
          echo repo.name: ${{github.event.repository.name}}
          prefix="build-your-own-"
          repo=${{github.event.repository.name}}
          slug="${repo#$prefix}"
          echo slug: $slug
          ls -lah $HOME
          ls -lah "$HOME/$slug"
          if [ -d "$HOME/$slug"]; then
            echo $slug "tester directory exists."
          else
            echo $slug "tester directory does not exist."
            exit 1
          fi
        shell: bash
