name: Test Course Definition

on:
  workflow_call:
    inputs:
      sdkRef:
        required: false
        type: string
        default: main

jobs:
  identify_language_slugs:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    outputs:
      language_slugs: ${{ steps.generate-language-slugs.outputs.language_slugs }}

    steps:
      - uses: actions/checkout@v3

      - name: Generate Language Slugs
        id: generate-language-slugs
        run: |-
          LANGUAGE_SLUGS=$(ls solutions | jq -Rnc '[inputs]')
          echo ::set-output name=language_slugs::${LANGUAGE_SLUGS}

  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    timeout-minutes: 20

    needs:
      - identify_language_slugs

    strategy:
      matrix:
        language: ${{ fromJSON(needs.identify_language_slugs.outputs.language_slugs) }}

    steps:
      - uses: oven-sh/setup-bun@v1

      - uses: actions/checkout@v3
        with:
          repository: "andy1li/course-sdk"
          ref: ${{inputs.sdkRef}}

      - run: bun install
      - run: make install

      - uses: actions/checkout@v3
        with:
          path: courses/${{github.event.repository.name}}

      - run: "echo ::remove-matcher owner=go::" # Messes with our output

      # - uses: depot/setup-action@v1
      # - uses: depot/build-push-action@v1
      #   with:
      #     project: tsp80qbtxw
      #     context: .
      #     load: true
      #     tags: tester:depot

      - run: git config --global user.email "hello@codecrafters.io"
      - run: git config --global user.name "codecrafters-bot"

      - run: course-sdk test ${{matrix.language}} && cp -r /tmp/testers/${{matrix.language}} $HOME/
        working-directory: courses/${{github.event.repository.name}}

      - name: sanity-check
        run: |
          ls -lah $HOME
          ls -lah $HOME/testers/${{matrix.language}}
          if [ -d $HOME/testers/${{matrix.language}} ]; then
            echo ${{matrix.language}} "tester directory exists."
          else
            echo ${{matrix.language}} "tester directory does not exist."
            exit 1
          fi
        shell: bash

      # "[ -d $HOME/sqlite ] && exit 1"
      # - run: "[ ! -d $HOME/sqlite ] && exit 1"
      # - run: "[ ! -d /tmp/testers/sqlite ] && exit 1"

      # - name: Start time
      #   id: starttime
      #   run: echo "start_time=$(date +%s)" >> $GITHUB_ENV

      # - run: course-sdk test ${{matrix.language}}
      #   working-directory: courses/${{github.event.repository.name}}

      # - name: End time and calculate duration
      #   id: endtime
      #   run: |
      #     echo "end_time=$(date +%s)" >> $GITHUB_ENV
      #     duration=$(( ${{ env.end_time }} - ${{ env.start_time }} ))
      #     echo "duration=$duration" >> $GITHUB_ENV
      #     echo ::set-output name=duration::$duration

      # - name: Check duration
      #   if: steps.endtime.outputs.duration < 60
      #   run: |
      #     echo "The previous step took less than one minute, failing the job."
      #     exit 1
